<?php

require './vendor/autoload.php';
require './PinterestCookieApi.php';
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$pin = new \NhanChauKP\Pinterest\PinterestCookieApi('TWc9PSZNTkhJU1c5UXJkelV4ZE9JcXlSVFUzWGdBb25qVTcycmNsV1ZmRXY0RFV5WDFSYTB5aUJGa1pGaUdaeGc4aGtDWTZYRDhBOXIrQ3A2RTFxRHlzREtjSDllZjE5UzhnQS9pTkpTNFlzcm03M3o3cm50V1lCclVVSXBOSi9YcmhNWDN6bmpxTGw1T1VpazlEbWtLUEI1UjdaKzlUbmpsT3Z6NWZZTnFFUmtZdmdsZnpyVkdmMy9vYUtuaXo1b0hCQnZ1UUgrTnVjeGd0TkFxSDhvZEtNc3Z2LzRMeFpTdW0rOUpjUElSdGxlc0V5RENWQUhjWmR4ZFNBVUMwZjFrUU5Oc0g5QWRDUGl6cHdXV2ZLMXdndXpaeGVMZi9JcGxPMTRFbFljcng1N0VIa0xYbFdQVjhveHVWM2Q3K2EzbUZ4SGkreHJCamkwQkpaMHZBSDRSVFBkV082ckZORXRFTEZIbWZuYlgyalpWT1UyTFBqbFpEMU5Ia2Z5M1Bocis1bkM5NnFJNTJianJ1VW9uSURXRnFtckY4VGdWaFpXUXJqbkRwdWVrL0MzVC9xY25lbVVQM0p1d2Ftb3RkYUxFT0pwOFg5VUprVUdDWkRJMFE2bk1oS2JBQlA2aFJ5dy9nb1VJN0o2bm40VnE5RS9uTExDZEtGU05UaFpSY24zdzRMMllKNmRHVmhxUHFwTkVzMnA4MGVLMkFyWXM5Ri9nN1BMNEp2VlJYRjN0bjlRRGZWbzI5bm9BMSt6RzZFN0F6Z0RGK0lrT3Job012VGdEYkwvaFU1NnVsSWdLdVBlVEJ0cGJ6U1NYMkhDdEdRQk55R2tGUHRGVDNmcmpicllHRjJJNjJCQWYrbG1yOWlYekhvbmVKek9BNy9ZQzdwMkVUSzJ5ZC9jVEs4SGlBMlFBbmRMU0lBVXcvVkNMdzJDY0JhcGJzRmN3dWJ6R0FjZEdhUWtkTnBnUnFLcUYzWVRhZGJxbzgvQjFZWGtzb01TT3dpVWtPb3lyeHlNY2VUaFNLRnB3aXBYOWRleUNzTHNWWTFHVk1peWlBPT0mTHZvaEdYbWkvOTJ1TUgwZFZCc1RhT2ZsMnVzPQ==', null);
$account = $pin->getAccountData();

var_dump($account);
